### ISSUE TITLE
linked issue

### ISSUE THREAD

**Issue by Johnjihwan** [siwony/TIL#13]
<img width="332" alt="Screen Shot 2021-06-17 at 4 02 01 PM" src="https://user-images.githubusercontent.com/67095821/122347777-5e064000-cf85-11eb-8dcd-a1e93646db42.png">

디자인 패턴 모두 linked `404 not found error`가 뜨네요.

**Comment by siwony** [comment]
지금 해결하고 있습니다. 알려주셔서 감사합니다 :)
