### ISSUE TITLE
오류 있습니다 ㅡㅡ

### ISSUE THREAD

**Issue by Sinawe4** [siwony/TIL#2]
const path = require('path');

module.exports = {
    'config': path.resolve('src/db/config/config.js'),
    'models-path': path.resolve('src/db/models'),
    'seeders-path': path.resolve('src/db/seeders'),
    'migrations-path': path.resolve('src/db/migrations')
}
부분을
module.exports = {
    'config': path.resolve('src/db/config/config.json'),
    'models-path': path.resolve('src/db/models'),
    'seeders-path': path.resolve('src/db/seeders'),
    'migrations-path': path.resolve('src/db/migrations')
}
으로 바꿔주셔야 합니다, 덕분에 30분동안 고생했네요 ㅎㅎ

**Comment by siwony** [comment]
아.... 죄송합니다. 고쳤습니다!
