### ISSUE TITLE
DAO, DTO, Entity Class 차이 및 package 구조에 대한 오류

### ISSUE THREAD

**Issue by MagicalLas** [siwony/TIL#3]
> Entity 클래스는 실제 DataBase의 테이블과 1 : 1로 매핑 되는 클래스로, DB의 테이블내에 존재하는 컬럼만을 속성(필드)으로 가져야 한다.
> Entity 클래스는 상속을 받거나 구현체여서는 안되며, 테이블내에 존재하지 않는 컬럼을 가져서도 안된다.

사실 그렇지 않습니다. entity는 데이터베이스를 알고있을 수도 있지만, 그러면 테스트하기 어려워지기에 DI를 사용하는 추세입니다. entity를 repository에 저장하는 것이고, 그것을 위해 DB를 사용하는 것이지 DB row를 코드에 나타내기위하여 entity를 사용하는 것은 아닙니다.

> DTO(Data Transfer Object) or VO(Value Object)

이부분도 다른 경우가 많습니다. (사실 이건 java진영에서 VO라는 단어를 잘못 쓰고있는경우에요)
VO와 DTO를 구분해서 사용하는 경우가 많습니다.

See Also: https://martinfowler.com/bliki/ValueObject.html

**Comment by siwony** [comment]
감사합니다

**Comment by siwony** [comment]
오류부분 제거 했습니다. spring 입문..... 어렵네요
