### ISSUE TITLE
안녕하세요, 마크다운 개발자 입니다.

### ISSUE THREAD

**Issue by Johnjihwan** [siwony/TIL#5]
TIL 인상깊게 잘 봤습니다.
약간 '미' 적으로 해치는 구간이 있어 issue를 답니다.
@siwony 님의 TIL h1 밑의 description을 좀 더 한줄로 간결하게. 작성 부탁합니다.

**Comment by siwony** [comment]
네 그부분 참고해서 수정하도록 하겠습니다. 감사합니다 👎
